### ISSUE TITLE
PyPI and github versions are mismatching

### ISSUE THREAD

**Issue by wronglink** [isagalaev/elementflow#11]
Hi. I can find no repository version matching last [PyPI release](https://pypi.python.org/pypi/elementflow) (0.5). It looks like the last released version was bumped from 0.4.2, but not pushed to github (the `elementflow.py` sources are the same).
Is there any way it could be updated?

**Comment by isagalaev** [comment]
Sorry for the slow response! Looks like I simply forgot to commit the setup.py with the version change. Just committed and pushed.
